### ISSUE TITLE
Unable to use on mobile device

### ISSUE THREAD

**Issue by cleversprocket** [PopSugar/angular-slider#11]
The bubble will not drag on mobile device. I see the bubble is getting the touch event because it lights up, but it cannot be dragged. Can you test to see if this happens across the board and not just for me?

The error I see in the console is:
Uncaught TypeError: Cannot read property '0' of undefined

All files seem to get minified when using Chrome's ADB plugin inspector so I can't debug it :(

This is how I'm using it:
`<slider floor="0" ceiling="18" step="1" precision="0" ng-model="colorSlider.position"></slider>`

$scope.colorSlider = {
            position: 0
        };

I'm using Angular 1.3 and I also couldn't get it to work with angular 1.2.

**Comment by unscsprt** [comment]
I'm having the same issue, the handles aren't movable on mobile. I'm using jQuery 2.1.3 and Angular 1.3.7.

**Comment by that70schris** [comment]
@cleversprocket and @unscsprt, I've fixed the offending line in v0.2.11, can you test that version out and let me know how it works?

**Comment by unscsprt** [comment]
@that70schris The slider responds to touch events now, but the behavior is erratic. In my case, the first touch sets the first handle to the lower limit, then the second touch sets the second handle to the lower limit, and neither are movable at that point.

**Comment by cleversprocket** [comment]
Looks like you're using underscore with this fix? I can't test because I get the error that '_' is not defined.

**Comment by unscsprt** [comment]
@cleversprocket I just imported underscore so I could test it. But then I got an error at line 52, where it says ``'if (_.isInt(value)) {...```.

It doesn't look like .isInt() is in the latest underscore?

Just replace that condition with ```if (value % 1 === 0) { ...``` and you should be good.

**Comment by cleversprocket** [comment]
Thanks @unscsprt , but after trying that it still doesn't work. I'm not seeing any errors in the console.

**Comment by unscsprt** [comment]
@cleversprocket Yeah, I was just describing how to fix the console errors haha. Are you having the same issue I described [here](https://github.com/PopSugar/angular-slider/issues/11#issuecomment-69018130) earlier?

**Comment by cleversprocket** [comment]
@unscsprt I'm only using one handle and the default position is zero. When I have more time I can set the default at something other than zero but if its not sliding at all then I don't see the point.

**Comment by that70schris** [comment]
my apologies everyone, isInt is an internal function we've added to underscore, fixing now

**Comment by that70schris** [comment]
ok I've removed the underscore dependency in v0.2.12

**Comment by cleversprocket** [comment]
@that70schris it's not working for me. No errors in the console.

**Comment by that70schris** [comment]
@unscsprt does v0.2.12 work for you? I just tried using your example and everything seems to work fine for me on mobile.  Same with yours @cleversprocket

**Comment by laurentClave** [comment]
No work for me :(

**Comment by unscsprt** [comment]
@that70schris Here's the issue I'm having using v0.2.12 ![gif](http://zippy.gfycat.com/GleefulInformalBluegill.gif).

Same thing happens on iPhone. Here's how I'm using it (same as above):

```
<slider floor="10" ceiling="250" step="5" ng-model-low="newJob.salary_min" ng-model-high="newJob.salary_max"></slider>
```

**Comment by that70schris** [comment]
@unscsprt, please give v0.2.13 a try

**Comment by that70schris** [comment]
scratch that, back to the drawing board

**Comment by unscsprt** [comment]
Haha okay. With v0.2.13, the handles stay in the same position and aren't movable, but they change color, so I guess it's at least recognizing the touch event.

**Comment by that70schris** [comment]
@unscsprt I really don't understand at this point why I can get your implementation to work and you can't.  is there anything else you're doing differently?

**Comment by unscsprt** [comment]
@that70schris I really appreciate your taking the time to help with this. What device / browser are you testing it in? I shouldn't be doing anything differently, which is why I'm confused too. Do we know what dependency changed that broke touch functionality in the first place?

**Comment by that70schris** [comment]
I'm testing in iOS Simulator.  I can't think of any dependency recently added

**Comment by unscsprt** [comment]
That's so weird, it's doing the same thing for me in iOS Simulator. I'm going to keep working on this, I must be doing something wrong.

**Comment by that70schris** [comment]
Thanks for looking into it, you're not the only one experiencing the same behavior though so either:
A. we have a dependency somewhere that we missed
B. multiple people are doing the same wrong thing

**Comment by unscsprt** [comment]
Okay I might be onto something. I thought it might depend on angular-touch.js. Apparently not. Then I put print statements in each of the ```bindToInputEvents.onEnd, onMove, and onStart```. Works as you'd expect on desktop, but then it gets weird with touch. Start/end only print if you touch but don't move, like touch and release w/o dragging. Otherwise nothing prints. So that might say something about how the events are being handled.

**Comment by that70schris** [comment]
interesting, in light of that, I thought the fact that we use [FastClick](https://github.com/ftlabs/fastclick) might have something to do with, but just tried removing it from our project and the slider still works on mobile so we can eliminate that possibility

**Comment by unscsprt** [comment]
What's the order that you're importing jQuery, AngularJS, slider, etc. in? I read something that said if Angular falls back to jQlite because jQuery isn't available when it loads it might cause problems, but I don't think that's my issue.

**Comment by that70schris** [comment]
we actually don't use jQuery

**Comment by sifu** [comment]
i have a pull request that fixes the issue for me:
https://github.com/PopSugar/angular-slider/pull/18

i'm using the changedTouches from the original event.

**Comment by that70schris** [comment]
@sifu I have merged your changes, can you try v0.2.14 to see if your issue has been resolved as well?

**Comment by cleversprocket** [comment]
@that70schris the fix works for me! Thanks @sifu and @that70schris

**Comment by unscsprt** [comment]
This fix also works for me! Thank you @sifu and @that70schris, I think we can close this issue now @cleversprocket.

**Comment by laurentClave** [comment]
Also works for me ;)
Thank!

**Comment by that70schris** [comment]
excellent, thanks everyone!
